import Head from 'next/head'
import { Box, Typography } from '@mui/material'
import React from 'react'
import SideBar from '../src/Components/SideBar'
import SimpleTypegraphy from '../src/Components/SimpleTypegraphy'
import Table from '../src/Components/OrdersTable/index'
import SidebarLayout from '../src/Layouts/sideBarLayout'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Order app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
      </Head>

      <main>
        
        <Box sx={{paddingLeft:"150px",paddingTop:"40px",paddingRight:"48px"}}>
            <SimpleTypegraphy text="Buyurtmalar" className="order__title" variant={"h2"}/>
            <Table/>
        </Box>
      </main>

    </div>
  )
}
